# Default values for template-node-typescript.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

replicaCount: 1
logLevel: "debug"

image:
  repository: replace
  tag: replace
  pullPolicy: IfNotPresent
  port: 3000

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

route:
  enabled: false

ingress:
  enabled: true
  appid:
    enabled: true
    # web or app - https://cloud.ibm.com/docs/services/appid?topic=appid-kube-auth
    requestType: web
    binding:
      name: "binding-sandbox-ocp431-one-appid"
      namespace: dev5-yks

#  host: hello
  namespaceInHost: true
  subdomain: sandbox-ocp431-on-651721-89dadfe96916fcd27b299431d0240c37-0000.eu-gb.containers.appdomain.cloud
  path: "/"

#  tlsSecretName: ""

vcsInfo:
  repoUrl: ""
  branch: ""

partOf: ""

connectsTo: ""

runtime: js



